name: NGINX Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  TF_ROOT: "./nginx-hello/"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "${{ secrets.DOCKERUSERNAME }}" --password-stdin
        docker image build -t "${{ secrets.DOCKERUSERNAME }}"/nginx-hello:latest .
        docker push "${{ secrets.DOCKERUSERNAME }}"/nginx-hello:latest
      working-directory: "${{ env.TF_ROOT }}"
